fruits = ['orange','apple','pear','banana','kiwi','banana']
a= fruits.count("apple")
print("apple number =" ,a)
index_of_banana=fruits.index('banana')
print ("The index of banana:  ", index_of_banana)
index_of_banana_2=fruits.index('banana',4)
print ("The index of banana, 4: ", index_of_banana_2)
fruits.reverse()
print (fruits)
#print ("The revers of fruits list: ", reverse_1)
append_of_grape= fruits.append("grape")
print ("The append of  grape: ", append_of_grape)
sorte_list= fruits.sort()
print ("Sortting of fruits list: ", sorte_list)
pop_list= fruits.pop()
print ("pop  list : ", pop_list)
#print (fruits)